ALTER TABLE products
  ADD COLUMN isSellable BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN purchasePrice DECIMAL(10,2) NULL;

ALTER TABLE cartItems
  ADD COLUMN rentalDate DATE NULL;

ALTER TABLE rentalBookings
  ADD COLUMN quantity INT NOT NULL DEFAULT 1,
  ADD COLUMN rentalPrice DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN payments DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN remaining DECIMAL(10,2) NOT NULL DEFAULT 0;
